# Docker compose file to configure an existing ESGF Solr Cloud cluster

version: '3.4'

services:

  # Container that executes Solr configuration after Solr servers have started
  # REQUIREMENT: num_shards * replication_factor <= num_nodes * max_shard_per_node
  solr-config:
    image: solr:7.4
    container_name: solr-config
    entrypoint: /usr/local/scripts/solr_config.sh
    environment:
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      SOLR_HOST: solr-node-1
      SOLR_PORT: 8983
      SOLR_NUM_SHARDS: 2
      SOLR_NUM_REPLICAS: 2
      SOLR_MAX_SHARDS_PER_NODE: 3
    volumes:
      - ./scripts:/usr/local/scripts
      - ./solr/solr-home/conf:/esgf/solr-home/conf
   
networks: 
  default:
    external: 
      name: solr-network 
  
