# Docker compose file to configure an existing ESGF Solr Cloud cluster

version: '3.4'

services:

  # Container that executes Solr configuration after Solr servers have started
  # REQUIREMENT: num_shards * replication_factor <= num_nodes * max_shard_per_node
  solr-config:
    image: solr:7.4
    container_name: solr-config
    #entrypoint: /src/esgf-solr-cloud/scripts/solr_config.sh
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      SOLR_HOST: solr-node-1
      SOLR_PORT: 8983
      SOLR_NUM_SHARDS: 2
      SOLR_NUM_REPLICAS: 2
      SOLR_MAX_SHARDS_PER_NODE: 3
    volumes:
      # parent directory
      - ${PWD}/..:/src/esgf-solr-cloud
   
networks: 
  default:
    external: 
      name: solr-network 
  
