
version: '3.4'

services:

  harvester:
    image: esgfhublc/esgfpy-publish
    container_name: harvester
    #entrypoint: /usr/local/bin/solr_harvest.sh
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      # script in parent directory
      - ${PWD}/../scripts/solr_harvest.sh:/usr/local/bin/solr_harvest.sh
    
   
networks: 
  default:
    external: 
      name: solr-network 
  
